FROM dtzar/helm-kubectl

ARG CONTAINER_REGISTRY
ENV CONTAINER_REGISTRY ${CONTAINER_REGISTRY}

ARG CONTAINER_REGISTRY_USERNAME
ENV CONTAINER_REGISTRY_USERNAME ${CONTAINER_REGISTRY_USERNAME}

ARG CONTAINER_REGISTRY_PASSWORD
ENV CONTAINER_REGISTRY_PASSWORD ${CONTAINER_REGISTRY_PASSWORD}

ENV APP_HOME /app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

COPY . .

ENV HELM_EXPERIMENTAL_OCI 1
COPY scripts/deploy-helm-entrypoint.sh ${APP_HOME}/k8
WORKDIR ${APP_HOME}/k8

ENTRYPOINT ["sh", "deploy-helm-entrypoint.sh"]
