#!/bin/bash

HELM_CHART_NAME=dev-workspace
docker build -t deploy-helm .
docker run \
  --env HELM_CHART_NAME=$HELM_CHART_NAME \
  --env CONTAINER_REGISTRY=$CONTAINER_REGISTRY \
  --env CONTAINER_REGISTRY_USERNAME=$CONTAINER_REGISTRY_USERNAME \
  --env CONTAINER_REGISTRY_PASSWORD=$CONTAINER_REGISTRY_PASSWORD \
  deploy-helm